---
title: "Local Projections Difference-in-Differences"
author: "Alexander Cardazzi"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Local Projections Difference-in-Differences}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Getting Started

Please see the working paper on which this package is based [here](https://www.nber.org/papers/w31184).

To install and load this package, use the following code:

```{r include=FALSE}
devtools::load_all(".")
par(mar = c(4.1, 4.1, .1, 4.1))
```

```{r eval=FALSE}
if(!"devtools" %in% installed.packages()) install.packages("devtools")
if(!"lpdid" %in% installed.packages()) devtools::install_github("alexCardazzi/lpdid")
library("lpdid")
```

## A Simple 2x2 DiD Example

```{r, fig.width=7, fig.height=5, fig.align='center', cache=TRUE}
set.seed(757)
I <- 50; T <- 50; N <- I * T
data.frame(id = rep(1:I, each = T),
           t = rep(1:T, I),
           e = rnorm(N, 0, 4)) -> df
unit_FE <- rnorm(I, 0, 4)
time_FE <- rnorm(T, 0, 4)
df$treated <- ifelse(df$id < 21, 1, 0)
df$time_til <- ifelse(df$treated == 1, df$t - 30, -1)
df$y <- df$e + unit_FE[df$id] + time_FE[df$t] + ifelse(df$id < 21 & df$t > 30, df$t - 30, 0)
aggregate(df$y, list(df$t, df$treated), mean) -> tmp
plot(tmp$Group.1, tmp$x, col = tmp$Group.2 + 1, pch = 19,
     xlab = "Time", ylab = "Outcome")
lpdid(df, window = c(-20, 20), y = "y",
      unit_index = "id", time_index = "t",
      reweight = FALSE,
      rel_time = "time_til") -> reg

plot_lpdid(reg)
```

## Staggered (Exogenous) Treatment Timing

```{r, fig.width=7, fig.height=5, fig.align='center', cache=TRUE}
df <- genr_sim_data(exogenous_timing = TRUE, 789)
twfe1 <- feols(y ~ i(rel_time, ever_treat, -1) | i + t, data = df)
lpdid1 <- lpdid(df, window = c(-5, 10), y = "y",
                unit_index = "i", time_index = "t", rel_time = "rel_time")
plot_lpdid(lpdid1, col = "tomato", x.shift = 0.1)
iplot(twfe1, add = TRUE)
points(aggregate(df$beta[df$ever_treat == 1], list(df$rel_time[df$ever_treat == 1]), mean))
legend("topleft", c("True Beta", "TWFE", "LP-DiD"), bty = "n",
       pch = c(1, 19, 19), col = c("black", "black", "tomato"))
```

## Staggered (Endogenous) Treatment Timing

```{r, fig.width=7, fig.height=5, fig.align='center', cache=TRUE}
df <- genr_sim_data(exogenous_timing = FALSE, 789)
twfe1 <- feols(y ~ i(rel_time, ever_treat, -1) | i + t, data = df)
lpdid1 <- lpdid(df, window = c(-5, 10), y = "y", outcome_lags = 1,
                unit_index = "i", time_index = "t", rel_time = "rel_time")
plot_lpdid(lpdid1, col = "tomato", x.shift = 0.1)
iplot(twfe1, add = TRUE, x.shift = -0.1)
points(aggregate(df$beta[df$ever_treat == 1], list(df$rel_time[df$ever_treat == 1]), mean))
legend("topleft", c("True Beta", "TWFE", "LP-DiD"), bty = "n",
       pch = c(1, 19, 19), col = c("black", "black", "tomato"))
```

## The ```castle``` Dataset

```{r, fig.width=7, fig.height=5, fig.align='center', cache=TRUE}
library("fixest")
df <- bacondecomp::castle

df$t <- df$year - df$treatment_date
ifelse(is.na(df$t), -1, df$t) -> df$t
df$treat <- ave(df$post, df$state, FUN = max)
twfe1 <- feols(l_homicide ~ i(t, treat, -1) | state + year, data = df)

df$treatment_date1 <- ifelse(is.na(df$treatment_date), 3000, df$treatment_date)
sunab1 <- feols(l_homicide ~ sunab(treatment_date1, year)
               | state + year, data = df)

lpdid(df = df,
      window = c(-19, 10),
      y = "l_homicide",
      unit_index = "state",
      time_index = "year",
      rel_time = "t") -> reg

par(mfrow = c(1,1))
plot_lpdid(reg, col = "tomato")
iplot(sunab1, add = TRUE, col = "dodgerblue", x.shift = 0.15)
iplot(twfe1, add = TRUE, col = "black", x.shift = -0.15)
legend("bottomright", c("TWFE", "LP-DiD", "Sun & Abraham"),
       col = c("black", "tomato", "dodgerblue"), pch = 15,
       bty = "n")
```

## Andrew Baker's Simulated Dataset

```{r, fig.width=7, fig.height=5, fig.align='center', warning=FALSE, cache=TRUE}
baker <- haven::read_dta('https://github.com/scunning1975/mixtape/raw/master/baker.dta')
baker$treated <- baker$treat_date != 0

tmp <- aggregate(list(y = baker$y),
                 list(year = baker$year,
                      group = baker$group),
                 mean)
plot(tmp$year, tmp$y, pch = 19,
     col = scales::alpha(tmp$group, .4),
     xlab = "Year", ylab = "Outcome")
lines(tmp$year[tmp$group == unique(tmp$group)[1]],
      tmp$y[tmp$group == unique(tmp$group)[1]],
      col = tmp$group[tmp$group == unique(tmp$group)[1]])
lines(tmp$year[tmp$group == unique(tmp$group)[2]],
      tmp$y[tmp$group == unique(tmp$group)[2]],
      col = tmp$group[tmp$group == unique(tmp$group)[2]])
lines(tmp$year[tmp$group == unique(tmp$group)[3]],
      tmp$y[tmp$group == unique(tmp$group)[3]],
      col = tmp$group[tmp$group == unique(tmp$group)[3]])
lines(tmp$year[tmp$group == unique(tmp$group)[4]],
      tmp$y[tmp$group == unique(tmp$group)[4]],
      col = tmp$group[tmp$group == unique(tmp$group)[4]])

res_naive = feols(y ~ i(time_til, treated, ref = -1) | 
                    id + year,
                  baker, cluster = ~state)

res_cohort = feols(y ~ sunab(treat_date, year) | id + year, 
                   baker[baker$year<2004,],
                   cluster = ~state)

lpdid(df = baker, window = c(-20, 20), y = "y",
      unit_index = "id", time_index = "year",
      rel_time = "time_til", reweight = TRUE) -> reg

iplot(res_naive, col = "black", grid = F,
      xlab = "Time to Treatment", main = "")
iplot(res_cohort, col = "dodgerblue", add = TRUE)
plot_lpdid(reg, add = TRUE, col = "tomato", pch = 1, cex = 1.5)
legend("topright", col = c("black", "tomato", "dodgerblue"),
       pch = c(20, 20, 1), bty = "n",
       legend = c("TWFE", "Sun & Abraham", "LP-DiD"))
```

## Non-Absorbing Treatment

```{r, fig.width=7, fig.height=5, fig.align='center'}
set.seed(757)
I <- 50; T <- 50; N <- I * T; e_var <- 4
data.frame(id = rep(1:I, each = T),
           t = rep(1:T, I),
           e = rnorm(N, 0, e_var)) -> df
unit_FE <- rnorm(I, 0, e_var)
time_FE <- rnorm(T, 0, e_var)
df$treated <- ifelse(df$id < 21, 1, 0)
df$treat_status <- ifelse(df$id < 21 & df$t %in% 16:25, 1, 0)
df$treat_status <- ifelse(df$id < 11 & df$t %in% 36:45, 1, df$treat_status)
df$y <- df$e + unit_FE[df$id] + time_FE[df$t] +
  ifelse(df$id < 11,
         ifelse(df$t > 35, 50,
                ifelse(df$t > 15, 15, 0)),
         ifelse(df$id < 21,
                ifelse(df$t > 15, 15, 0),
                0))
df$group <- (ave(df$treat_status, df$id)) * 5

agg <- aggregate(df$y, list(df$t, df$group), mean)
plot(agg$Group.1, agg$x, col = agg$Group.2 + 1, pch = 19)

lpdid(df = df, window = c(-12, 12), y = "y",
      unit_index = "id", time_index = "t",
      reweight = FALSE,
      nonabsorbing = TRUE, nonabsorbing_lag = 5,
      nonabsorbing_treat_status = "treat_status",
      rel_time = "") -> reg

ci <- 1.96*reg$coeftable$`Std. Error`
b <- reg$coeftable$Estimate
plot(reg$window, reg$coeftable$Estimate, pch = 19,
     ylim = range(b + ci, b - ci),
     xlab = "", ylab = "")
segments(x0 = reg$window, lty = 1, col = "black",
         y1 = b + ci, y0 = b - ci)
abline(v = -1, h = 0)
abline(h = mean(c(15, 15, 50 - 15)), lty = 2)
```


## Things Under Construction

- Thing 1
- Thing 2
